### PR TITLE
 use roocs config in tests

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR updates the tests. It generates a roocs config file used by daops in tests.

Changes:

* skip mock test, use generated roocs.ini
* removed unused config
* added roocs.ini
* added dev versions of daops etc to conda env

## Additional Information

#33

### CODE REVIEW

**Review by ellesmith88 — COMMENTED** [review]
@cehbrecht Looks good, should we put the config file created by the template into `.gitignore`? or do you think it's fine as it is?

**Comment by cehbrecht** [comment]
> @cehbrecht Looks good, should we put the config file created by the template into `.gitignore`? or do you think it's fine as it is?

Currently it is writing the generated config file to a temp folder outside of the git source dir.

**Comment by ellesmith88** [comment]
> > @cehbrecht Looks good, should we put the config file created by the template into `.gitignore`? or do you think it's fine as it is?
> 
> Currently it is writing the generated config file to a temp folder outside of the git source dir.

Ok, I was wondering about the `rook/etc/roocs.ini` file in the PR - looks like its file paths that are specific to you?

**Comment by cehbrecht** [comment]
> > > @cehbrecht Looks good, should we put the config file created by the template into `.gitignore`? or do you think it's fine as it is?
> > 
> > 
> > Currently it is writing the generated config file to a temp folder outside of the git source dir.
> 
> Ok, I was wondering about the `rook/etc/roocs.ini` file in the PR - looks like its file paths that are specific to you?

... just a config for local testing.

**Pull request merged**
