### PR TITLE
skip defaults in wps subset process

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR removes the default values in wps subset process. The `time` parameter is mandatory.

## Related Issue / Discussion

https://github.com/roocs/34e-mngmt/issues/42

### CODE REVIEW

**Comment by cehbrecht** [comment]
If `time` parameter is None it will fail in daops:
```
File "/Users/pingu/Documents/GitHub/roocs/rook/src/daops/daops/ops/subset.py", line 48, in subset
    parameters.get('collection'), time=parameters.get('time')
  File "/Users/pingu/Documents/GitHub/roocs/rook/src/daops/daops/utils/consolidate.py", line 40, in consolidate
    required_years = set(range(*[int(_.split('-')[0]) for _ in time]))
  File "/Users/pingu/Documents/GitHub/roocs/rook/src/daops/daops/utils/consolidate.py", line 40, in <listcomp>
    required_years = set(range(*[int(_.split('-')[0]) for _ in time]))
AttributeError: 'NoneType' object has no attribute 'split'
```

wps will complain now if `time` is missing.

**Comment by ellesmith88** [comment]
@cehbrecht I've seen the issue in `daops`, I have a fix almost ready

**Comment by ellesmith88** [comment]
@cehbrecht I've just merged the fix in daops so the tests should be ok now

**Comment by cehbrecht** [comment]
@ellesmith88 thanks :)

**Pull request merged**
