### PR TITLE
Update average parameters

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR updates adds the processes `average_time` and `average_dim`. 

Changes:
* new processes `average_time` and `average_dim` calling the corresponding daops operators.
* updated tests

## Related Issue / Discussion

https://github.com/roocs/daops/pull/90

## Additional Information

Later we can still add a "meta" `average` operator with an `aggregation type` for the `average` operations with values like:
"annual", "monthly", "level", "model", "country", ...

### CODE REVIEW

**Comment by agstephens** [comment]
Hi @cehbrecht, thanks for putting this together. Do you propose that `aggregation` would have a scope that is wider than temporal parameters? I.e. could you imagine it included values (later on) such as "model", "ensemble", "country"?

**Comment by cehbrecht** [comment]
> Hi @cehbrecht, thanks for putting this together. Do you propose that `aggregation` would have a scope that is wider than temporal parameters? I.e. could you imagine it included values (later on) such as "model", "ensemble", "country"?

I thought so. The `aggegation type` can imply the dimension used (time, area).

**Comment by cehbrecht** [comment]
@agstephens @ellesmith88 daops `average_over_dims` operator is using the parameter `dims`. In the WPS process I have chosen the singular `dim`, allowing multiple values. But in the workflow one needs to use `dims` for the daops. Could be confusing :) 

But when I run a WPS request with `Get` it looks like this:
```
DataInputs=dim=latitude;dim=longitude
```

https://github.com/roocs/rook/blob/c24255e981bd85d669db4a7d55ffa54947c7a015/tests/test_wps_average_dim.py#L38

**Comment by ellesmith88** [comment]
@cehbrecht All looks good! For the dimension parameter, could it be called dimensions/ dims, which allows one value and could then be parsed (like collection)? If not, I don't think it's too confusing 😄

**Comment by cehbrecht** [comment]
@ellesmith88 I'm using `dims` parameter now also for the WPS process definition.

**Pull request merged**
