### PR TITLE
fix build_metalink for urls returned by workflow

### PR DESCRIPTION
**Pull request by cehbrecht**
## Overview

This PR fixes `build_metalink` to set urls and files.

Changes:

* `build_metalink` figures out by itself it `file_uri` is a url or file.
* test added.

## Related Issue / Discussion

#92

### CODE REVIEW

**Comment by cehbrecht** [comment]
Test on dkrz demo wps node without updating dependencies:
```
cd /usr/local/src/rook
git fetch
git checkout fix-download
pip install --no-deps -e .
supervisorctl restart rook
```

The workflow request for original files works:
```
wf = ops.Subset(
            ops.Input(
                'rlds', ['CMIP6.CMIP.IPSL.IPSL-CM6A-LR.historical.r1i1p1f1.Amon.rlds.gr.v20180803']
            ),
            # time="1860-01-01/1920-12-30",
)
resp = wf.orchestrate()
```

**Comment by cehbrecht** [comment]
@ellesmith88 You might look at the same issue 😄 If so you can just pick what you like and we close this one. I want to let the `build_metalink` method decide by itself about the uri mapping to url or file. We can skip the `as_urls` parameter.

**Comment by ellesmith88** [comment]
> @ellesmith88 You might look at the same issue 😄 If so you can just pick what you like and we close this one. I want to let the `build_metalink` method decide by itself about the uri mapping to url or file. We can skip the `as_urls` parameter.

I think we're looking at different things - I'm trying out something like this issue  https://github.com/roocs/rook/issues/91, I'll merge your branch into mine to check 😄

**Comment by cehbrecht** [comment]
> > @ellesmith88 You might look at the same issue 😄 If so you can just pick what you like and we close this one. I want to let the `build_metalink` method decide by itself about the uri mapping to url or file. We can skip the `as_urls` parameter.
> 
> I think we're looking at different things - I'm trying out something like this issue #91, I'll merge your branch into mine to check 😄

I think that is the same issue. It happens when the metalink file gets a URL but is assigned to a file:
```
mf.file = 'https://data.node/test.nc'
```

**Comment by cehbrecht** [comment]
@ellesmith88 I did not run `black` for formatting. Should I? 

dropped the repo with `pre-commit` to avoid troubles with the git submodules 😉

**Comment by ellesmith88** [comment]
@cehbrecht  I think the formatting is ok because it hasn't raised any errors in the tests. This looks good to me though, but I'm wondering why the tests are failing?

**Comment by ellesmith88** [comment]
> @cehbrecht I think the formatting is ok because it hasn't raised any errors in the tests. This looks good to me though, but I'm wondering why the tests are failing?

Oh because this c3s_mapping branch hasn't been merged!

**Review by ellesmith88 — APPROVED** [review]

**Comment by cehbrecht** [comment]
@ellesmith88 Thanks for review :) Merged to master to have it in place.

**Pull request merged**
